name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "ForzaHorizon4"
  comment: "Forza Horizon 4 Latest Version"
  url: "https://cdn1.koyso.com/Forza.Horizon.4.v1.478.564.0.rar?verify=1730808647-SRxXvFYUtajkhyxiYgpDSMNHXpaCfvthuRRTVn6wzIk%3D"
  file_name: "Forza.Horizon.4.v1.478.564.0.rar"
  piece_size: 23 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
